config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get "users/:id/confirm" => "users#confirm", as: "user_confirm"
    patch "users/:id/deactivate" => "users#deactivate", as: "user_deactivate"
    resources :users, only: [:index, :show, :update]
    resources :posts, only: [:index, :show, :update] do
      resources :comments, only: [:show, :update]
    end
    get "reports/pending"
    resources :reports, only: [:index, :show, :update]
  end


  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in' => "public/sessions#new_guest"
  end

  scope module: :public do
    root to: "home#top"
    get "/home", to: "home#home"
    get "/policy", to: "home#policy"
    get '/search', to: "searches#search"
    resources :searches, only: [:new]

    get "users/:id/posts" => "users#posts", as: "user_posts"
    get "users/:id/welcome" => "users#welcome", as: "user_welcome"
    get "users/:id/confirm" => "users#confirm", as: "user_confirm"
    get "users/:id/by_category" => "users#by_category", as: "user_posts_by_category"
    patch "users/:id/withdraw" => "users#withdraw", as: "user_withdraw"
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resource :relationship, only: [:create, :destroy]
      get "friends" => "relationships#friends", as: "friends"
      get "followers" => "relationships#followers", as: "followers"
      get "following" => "relationships#following", as: "following"
    end

    get "/bookmarks" => "bookmarks#index"

    get "posts/drafts"
    get "posts/by_category"
    resources :posts do
      resource :bookmark, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:create]
    get "reports/en/new" => "reports#new_en", as: "new_report_en"
    resources :reports, only: [:new, :create, :show]
    patch "notifications/destroy_all"
    resources :notifications, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :subject_user, class_name: "User", optional: true, foreign_key: "subject_id"
  belongs_to :post, optional: true
  belongs_to :comment, optional: true

  validates :user_id, presence: true
  validates :model, presence: true
  validates :object_id, presence: true
  validates :category, presence: true
  validates :detail, presence: true

  enum category: {offensive: 0,
                  sexual: 1,
                  discriminatory: 2,
                  impersonation: 3,
                  inappropriate: 4,
                  other: 5
                  }

  default_scope -> {order('created_at desc')}

  def self.pending
    where(is_closed: false)
  end

end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @reports = Report.includes(:user, :post, :comment, :subject_user).page(params[:page])
  end

  def pending
    @reports = Report.pending.includes(:user, :post, :comment, :subject_user).page(params[:page])
  end

  def show
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    @report.update(report_params)
    redirect_to request.referer
    flash[:notice] = "The report has been successfully updated"
  end

  private
  def report_params
    params.require(:report).permit(:is_closed, :note)
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/_index.html.erb
<ul class="list-group">
  <li class="list-item d-flex small">
    <div class="col-1">No.</div>
    <div class="col-5 col-md-7">Subject</div>
    <div class="col-4 col-md-2">Reported on</div>
    <div class="col-1">Status</div>
  </li>
  <% reports.each do |report| %>
    <%= link_to admin_report_path(report), class: "btn btn-light border-bottom m-0 px-0" do %>
      <li class="list-item d-flex small">
        <div class="col-1 small"><%= report.id %></div>
        <div class="col-5 col-md-7 text-left small">
          <% if report.model == "user" %>
            <%= report.subject_user.name %>
          <% elsif report.model == "post" %>
            <%= report.post.title %>
          <% elsif report.model == "comment" %>
            Comment on <%= report.post.title %>
          <% end %>
        </div>
        <div class="col-4 col-md-2 text-left small"><%= report.created_at.strftime('%m/%d/%y %H:%M') %></div>
        <div class="col-1 small">
          <% if report.is_closed? %>
            <div class="text-danger">Closed</div>
          <% else %>
            Open
          <% end %>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/admin/reports/index.html.erb
<div class="admin-body mx-auto">
  <div class="row heading">
    <h2>All Reports</h2>
    <p class="mb-0 ml-auto pr-3"><%= link_to "See new reports", admin_reports_pending_path %></p>
  </div>
  <%= render "index", reports: @reports %>
  <div class="row justify-content-center">
    <%= paginate @reports %>
  </div>
</div>

app/views/admin/reports/pending.html.erb
<div class="admin-body mx-auto">
    <div class="row heading">
      <h2>Open Reports</h2>
      <p class="mb-0 ml-auto pr-3"><%= link_to "See all reports", admin_reports_path %></p>
    </div>
    <%= render "index", reports: @reports %>
    <div class="row justify-content-center">
      <%= paginate @reports %>
    </div>
</div>

app/views/admin/reports/show.html.erb
<div class="admin-body mx-auto">
  <div class="row heading">
    <h2>Case No. <%= @report.id %></h2>
    <% if @report.is_closed? %>
      <div class="mx-4 my-auto">
        <p class="text-danger mb-0">CLOSED</p>
      </div>
    <% end %>
    <div class="ml-auto">
      <%= link_to "Open reports", admin_reports_pending_path %> | <%= link_to "All reports", admin_reports_path %>
    </div>
  </div>
  <div class="container py-2">
    <table class="table col-7 mx-auto">
      <tbody>
        <tr>
          <td class="col-3">Reported by</td>
          <td><%= link_to @report.user.name, admin_user_path(@report.user) %></td>
        </tr>
        <tr>
          <td>Reported
            <span class="text-capitalize">
              <%= @report.model %>
            </span>
          </td>
          <td>
            <% if @report.model == "user" %>
              <%= link_to @report.subject_user.name, admin_user_path(@report.subject_id) %>
            <% elsif @report.model == "post" %>
              <%= link_to @report.post.title, admin_post_path(@report.post_id) %>
            <% elsif @report.model == "comment" %>
              comment: "<%= link_to @report.comment.content, admin_post_comment_path(id: @report.comment_id, post_id: @report.comment.post_id) %>" </br>
              on post <%= link_to @report.comment.post.title, admin_post_path(@report.post_id) %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Category</td>
          <td><%= @report.category %></td>
        </tr>
        <tr>
          <td>Details</td>
          <td><%= @report.detail %></td>
        </tr>
      </tbody>
    </table>
    <div class="report-status">
      <% if @report.is_closed? %>
        Note
        <div class="container">
          <p><%= @report.note %></p>
        </div>
        <a data-toggle="collapse" href="#update_report" role="button" aria-expanded="false" aria-controls="update_report">
          <small>Reopen this case?</small>
        </a>
        <div class="collapse" id="update_report">
          <%= form_with model: @report, url: admin_report_path(@report.id), method: :patch do |f| %>
            <div class="field">
              <%= f.label :note, class: "mb-0" %>
              <%= f.text_area :note, class: "form-control" %>
            </div>
            <div class="actions mt-1">
              <%= f.check_box :is_closed, checked_value: true %>
              <i class="fas fa-caret-left"></i> <%= f.label :is_closed, "Uncheck to reopen" %>&nbsp;
              <%= f.submit "Update" %>
            </div>
          <% end %>
        </div>
      <% else %>
        <p class="mb-1"><ins>Close this case</ins></p>
        <%= form_with model: @report, url: admin_report_path(@report.id), method: :patch do |f| %>
          <div class="field">
            <%= f.label :note, class: "mb-0" %>
            <%= f.text_area :note, class: "form-control" %>
          </div>
          <div class="actions mt-1">
            <%= f.check_box :is_closed, checked_value: true %>
            <%= f.label :is_closed, "Close" %>&nbsp;
            <%= f.submit "Update" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>