config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get "users/:id/confirm" => "users#confirm", as: "user_confirm"
    patch "users/:id/deactivate" => "users#deactivate", as: "user_deactivate"
    resources :users, only: [:index, :show, :update]
    resources :posts, only: [:index, :show, :update] do
      resources :comments, only: [:show, :update]
    end
    get "reports/pending"
    resources :reports, only: [:index, :show, :update]
  end


  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in' => "public/sessions#new_guest"
  end

  scope module: :public do
    root to: "home#top"
    get "/home", to: "home#home"
    get "/policy", to: "home#policy"
    get '/search', to: "searches#search"
    resources :searches, only: [:new]

    get "users/:id/posts" => "users#posts", as: "user_posts"
    get "users/:id/welcome" => "users#welcome", as: "user_welcome"
    get "users/:id/confirm" => "users#confirm", as: "user_confirm"
    get "users/:id/by_category" => "users#by_category", as: "user_posts_by_category"
    patch "users/:id/withdraw" => "users#withdraw", as: "user_withdraw"
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resource :relationship, only: [:create, :destroy]
      get "friends" => "relationships#friends", as: "friends"
      get "followers" => "relationships#followers", as: "followers"
      get "following" => "relationships#following", as: "following"
    end

    get "/bookmarks" => "bookmarks#index"

    get "posts/drafts"
    get "posts/by_category"
    resources :posts do
      resource :bookmark, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:create]
    get "reports/en/new" => "reports#new_en", as: "new_report_en"
    resources :reports, only: [:new, :create, :show]
    patch "notifications/destroy_all"
    resources :notifications, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/sidebar/_friends.html.erb
  <ul class="mx-3 list-unstyled">
    <li><%= link_to "Friends", user_friends_path(current_user) %></li>
    <li><%= link_to "Following", user_following_path(current_user) %></li>
    <li><%= link_to "Followers", user_followers_path(current_user) %></li>
    <li><%= link_to "See all users", users_path %></li>
  </ul>

app/views/layouts/sidebar/_menu.html.erb
<div id="accordion">
  <div id="headingFriends">
    <div class="d-flex">
      <p class="my-auto ml-2">Friends</p>
      <button class="btn collapsed ml-auto" data-toggle="collapse" data-target="#friends" aria-expanded="true" aria-controls="friends">
        <i class="fas fa-angle-down"></i>
      </button>
    </div>
  </div>
  <div id="friends" class="collapse" aria-labelledby="headingFriends" data-parent="#accordion">
    <%= render "layouts/sidebar/friends" %>
  </div>
  <div>
    <div id="headingPosts">
      <div class="d-flex">
        <p class="my-auto ml-2">Posts</p>
        <button class="btn collapsed ml-auto" data-toggle="collapse" data-target="#Posts" aria-expanded="true" aria-controls="Posts">
          <i class="fas fa-angle-down"></i>
        </button>
      </div>
    </div>
    <div id="Posts" class="collapse" aria-labelledby="headingPosts" data-parent="#accordion">
      <%= render "layouts/sidebar/posts" %>
    </div>
  </div>
</div>

app/views/layouts/sidebar/_posts.html.erb
<ul class="mx-3 list-unstyled">
  <li><%= link_to "Bookmarks", bookmarks_path %></li>
  <li><%= link_to "See all posts", posts_path %></li>
</ul>

app/views/layouts/sidebar/_rooms.html.erb
<ul class="mx-3 list-unstyled">
  <% current_user.rooms.first(5).each do |room| %>
    <% if room.is_valid? %>
      <li>
        <%= link_to room_path(room) do %>
          <% user = room.users_except(current_user) %>
          <%= user.name %>
          <% if room.unchecked_notifications(current_user).any? %>
            <i class="fas fa-circle new-message"></i>
          <% end %>
        <% end %>
      </li>
    <% end %>
  <% end %>
  <li><%= link_to "See all rooms", rooms_path %></li>
</ul>

app/views/layouts/sidebar/_user.html.erb
<div class="user-info row align-items-center my-3">
  <div class="col-5">
    <%= image_tag current_user.get_profile_image(50,50), class: "round rounded-circle" %>
  </div>
  <div class="col-6">
    <% if current_user.name_jap.present? %>
      <small><%= current_user.name_jap %></small>
    <% end %>
    <%= current_user.name %>
  </div>
</div>