config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get "users/:id/confirm" => "users#confirm", as: "user_confirm"
    patch "users/:id/deactivate" => "users#deactivate", as: "user_deactivate"
    resources :users, only: [:index, :show, :update]
    resources :posts, only: [:index, :show, :update] do
      resources :comments, only: [:show, :update]
    end
    get "reports/pending"
    resources :reports, only: [:index, :show, :update]
  end


  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in' => "public/sessions#new_guest"
  end

  scope module: :public do
    root to: "home#top"
    get "/home", to: "home#home"
    get "/policy", to: "home#policy"
    get '/search', to: "searches#search"
    resources :searches, only: [:new]

    get "users/:id/posts" => "users#posts", as: "user_posts"
    get "users/:id/welcome" => "users#welcome", as: "user_welcome"
    get "users/:id/confirm" => "users#confirm", as: "user_confirm"
    get "users/:id/by_category" => "users#by_category", as: "user_posts_by_category"
    patch "users/:id/withdraw" => "users#withdraw", as: "user_withdraw"
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resource :relationship, only: [:create, :destroy]
      get "friends" => "relationships#friends", as: "friends"
      get "followers" => "relationships#followers", as: "followers"
      get "following" => "relationships#following", as: "following"
    end

    get "/bookmarks" => "bookmarks#index"

    get "posts/drafts"
    get "posts/by_category"
    resources :posts do
      resource :bookmark, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:create]
    get "reports/en/new" => "reports#new_en", as: "new_report_en"
    resources :reports, only: [:new, :create, :show]
    patch "notifications/destroy_all"
    resources :notifications, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  enum gender: {male: 0, female: 1, other: 2}

  scope :active, -> { where(is_deactivated: :false).where.not(name: "Guest User")}
  scope :with_attached_profile_image, -> {includes(profile_image_attachment: :blob)}

  has_one_attached :profile_image
  has_many :posts, ->{order('created_at desc')}, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, ->{order('created_at desc')}, dependent: :destroy
  has_many :entries
  has_many :rooms, through: :entries
  has_many :messages, dependent: :destroy
  has_many :reports
  has_many :passive_reports, class_name: "Report", foreign_key: "subject_id"
  has_many :notifications
  has_many :active_notifications, class_name: "Notification", foreign_key: "sender_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "recipient_id", dependent: :destroy

  validates :name, presence: true

  #ゲストユーザー情報を探し、存在しなければ作成
  def self.guest
    find_or_create_by!(email: 'guest@nelc.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "Guest User"
    end
  end

  #profile imageがなければデフォルトを使い、画像サイズを任意のサイズに縮小する
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no-image.jpg', content_type: 'image/jpg')
    end
    profile_image.variant(auto_orient: true, resize_to_fill: [width, height]).processed
  end

  #friend follow関係
  def friends
    following & followers
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

  def followed_by?(user)
    followers.include?(user)
  end

  def is_friend_with?(user)
    following?(user) && followed_by?(user)
  end

  def has_room_with?(user)
    rooms = Entry.pluck(:room_id)
    Entry.find_by(user_id: user.id, room_id: rooms).present?
  end

  #検索
  def self.search_for(name, language, gender, content)
    user = User.active.where("name LIKE ?", "%"+name.to_s+"%")
                      .where("introduction LIKE ?", "%"+content.to_s+"%")
                      .with_attached_profile_image
                      .includes(:following, :followers)
    scope :male, -> {where(gender: "male")}
    scope :female, -> {where(gender: "female")}
    scope :other, -> {where(gender: "other")}
    if language == "Japanese"
      if gender == "male"
        user.male.where(native_language: "Japanese")
      elsif gender == "female"
        user.female.where(native_language: "Japanese")
      elsif gender == "other"
        user.other.where(native_language: "Japanese")
      else
        user.where(native_language: "Japanese")
      end
    elsif language == "English"
      if gender == "male"
        user.male.where(native_language: "English")
      elsif gender == "female"
        user.female.where(native_language: "English")
      elsif gender == "other"
        user.other.where(native_language: "English")
      else
        user.where(native_language: "English")
      end
    elsif gender == "male"
        user.male
    elsif gender == "female"
        user.female
    elsif gender == "other"
        user.other
    else
      user
    end
  end

  #フォロー通知
  def create_notification_follow(current_user)
    #過去のフォロー通知がないか確認
    record = Notification.where(sender_id: current_user.id, recipient_id: id, action: "follow")
    unless record.present?
      notification = current_user.active_notifications.new(
        recipient_id: id,
        action: "follow"
        )
      notification.save if notification.valid?
    end
  end

  def deactivate
    update(is_deactivated: true)
    posts.update_all(is_deleted: true)
    comments.update_all(is_deleted: true)
    active_relationships.destroy_all
    passive_relationships.destroy_all
    bookmarks.includes(:post).destroy_all
    messages.destroy_all
    entries.includes(room: :entries).each do |entry|
      room = entry.room
      room.entries.destroy_all
      room.destroy
    end
    active_notifications.destroy_all
    passive_notifications.destroy_all
  end

  #ユーザーの投稿のカテゴリー一覧
  def post_categories
    post_ids = Post.where(user_id: id).ids
    category_ids = PostCategory.where(post_id: post_ids).pluck(:category_id)
    Category.where(id: category_ids)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).includes(profile_image_attachment: :blob).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.includes(user: {profile_image_attachment: :blob}).page(params[:page]).per(6)
  end

  def update
    @user = User.find(params[:id])
    @user.update(is_deactivated: false)
    redirect_to admin_user_path(@user)
    flash[:notice] = "The user status has been successfully updated"
  end

  def confirm
    @user = User.find(params[:id])
  end

  def deactivate
    @user = User.find(params[:id])
    @user.deactivate
    redirect_to admin_user_path(@user)
    flash[:notice] = "The user has been deactivated"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/confirm.html.erb
<div class="admin-body mx-auto">
  <div class="container py-5 mx-auto">
    <h4 class="text-center">Deactivate <%= link_to @user.name, admin_user_path(@user) %> ?</h4>
    <div class="my-5">
      <p>Deactivating a user also affects the following:</p>
      <ul>
        <li>All posts created by the user will be flaged as "deleted"</li>
        <li>All comments created by the user will be flaged as "deleted"</li>
        <li>All relationships, such as following and followed, asocciated with this user will be destroyed</li>
        <li>All bookmarks created by the user will be destroyed</li>
        <li>All room entries data of the user will be destroyed</li>
      </ul>
    </div>
    <div class="text-center">
      <div class="delete-user">
        <input type="checkbox"> Confirm to proceed
        <div class="delete-btn my-2">
          <%= link_to "Delete", admin_user_deactivate_path(@user), method: :patch, class: "btn btn-warning" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="admin-body mx-auto">
  <div class="row heading">
    <h2>All Users</h2>
  </div>
  <div class="list-group">
    <% @users.each do |user| %>
      <%= link_to admin_user_path(user), class: "btn btn-light border-bottom" do %>
        <div class="list-item d-flex">
          <div class="col-1 align-self-center">
              <%= user.id %>
            </div>
          <div class="flex-grow-1 p-2">
            <div class="d-flex mb-0">
                <p>
                  <%= image_tag user.get_profile_image(40,40), class: "rounded rounded-circle" %>
                  <%= user.name %>
                </p>
                <% if user.is_deactivated? %>
                  <div class="text-danger small mx-3">Deactivated User</div>
                <% end %>
                <small class="text-muted ml-auto">Joined on <%= user.created_at.strftime("%m/%d/%y") %></small>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="row justify-content-center">
    <%= paginate @users %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="admin-body mx-auto">
  <div class="row">
    <div class="col-md-4 col-lg-3 text-center">
      <div class="row heading">
        <h2>User Info</h2>
        <% if @user.is_deactivated? %>
          <div class="mt-auto mx-2">
            <p class="text-danger">Deactivated User</p>
          </div>
        <% end %>
      </div>
      <%= image_tag @user.get_profile_image(80,80), class: "rounded rounded-circle img-border" %>
      <p class="font-weight-bold"><%= @user.name %></p>
      <p>Gender:
        <%= @user.gender %>
        <% if @user.gender.blank? %>
          <small>N/A</small>
        <% end %>
      </p>
      <p>Speaks: <%= @user.native_language %>
        <% if @user.native_language.blank? %>
          <small>N/A</small>
        <% end %>
      </p>
      <p>
        <%= @user.learning_language %>
        <% if @user.learning_language.blank? %>
          <small>N/A</small>
        <% end %>
      </p>
      <p><%= @user.introduction %>
        <% if @user.introduction.blank? %>
          <small>No introduction</small>
        <% end %>
      </p>
      <hr>
        <div class="user-status">
          <% if @user.is_deactivated? %>
            <%= link_to "Activate", admin_user_path(@user), method: :patch, class: "btn btn-light" %>
          <% else %>
            <%= link_to "deactivate", admin_user_confirm_path(@user), class: "btn btn-warning" %>
          <% end %>
        </div>
      <hr>
    </div>
    <div class="col-md-8 mt-3">
      <h4>Posts by this user <small>(<%= @posts.count %> posts)</small></h4>
      <div class="posts mt-3">
        <% if @posts.any? %>
          <%= render "admin/posts/index", posts: @posts %>
        <% else %>
          <p>No post</p>
        <% end %>
      </div>
    </div>
  </div>
</div>