config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get "users/:id/confirm" => "users#confirm", as: "user_confirm"
    patch "users/:id/deactivate" => "users#deactivate", as: "user_deactivate"
    resources :users, only: [:index, :show, :update]
    resources :posts, only: [:index, :show, :update] do
      resources :comments, only: [:show, :update]
    end
    get "reports/pending"
    resources :reports, only: [:index, :show, :update]
  end


  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in' => "public/sessions#new_guest"
  end

  scope module: :public do
    root to: "home#top"
    get "/home", to: "home#home"
    get "/policy", to: "home#policy"
    get '/search', to: "searches#search"
    resources :searches, only: [:new]

    get "users/:id/posts" => "users#posts", as: "user_posts"
    get "users/:id/welcome" => "users#welcome", as: "user_welcome"
    get "users/:id/confirm" => "users#confirm", as: "user_confirm"
    get "users/:id/by_category" => "users#by_category", as: "user_posts_by_category"
    patch "users/:id/withdraw" => "users#withdraw", as: "user_withdraw"
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resource :relationship, only: [:create, :destroy]
      get "friends" => "relationships#friends", as: "friends"
      get "followers" => "relationships#followers", as: "followers"
      get "following" => "relationships#following", as: "following"
    end

    get "/bookmarks" => "bookmarks#index"

    get "posts/drafts"
    get "posts/by_category"
    resources :posts do
      resource :bookmark, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:create]
    get "reports/en/new" => "reports#new_en", as: "new_report_en"
    resources :reports, only: [:new, :create, :show]
    patch "notifications/destroy_all"
    resources :notifications, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_header.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container">
    <div class="navbar-brand">
      NELC : Admin
    </div>
    <!-- smより大きいnavbar -->
    <div class="d-none d-md-block">
      <ul class="nav">
        <li class="nav-link">
          <%= link_to "Users", admin_users_path %>
        </li>
        <li class="nav-link">
          <%= link_to "Posts", admin_posts_path %>
        </li>
        <li class="nav-link">
          <%= link_to "Reports", admin_reports_pending_path %>
        </li>

        <li class="nav-link">
          <%= link_to "Log out", destroy_admin_session_path, method: :delete %>
        </li>
      </ul>
    </div>
    <!-- xsのnavbar -->
    <div class="d-block d-md-none">
      <ul class="nav">
        <li class="nav-link">
          <%= link_to "Reports", admin_reports_pending_path %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" id="navbarDropdown" role="button" data-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
            <i class="fas fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <li class="dropdown-item">
              <%= link_to "Users", admin_users_path %>
            </li>
            <li class="dropdown-item">
              <%= link_to "Posts", admin_posts_path %>
            </li>
            <div class="dropdown-divider"></div>
            <li class="dropdown-item"><%= link_to "Log out", destroy_admin_session_path, method: :delete %><small>　ログアウト</small></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_alert.html.erb
<% if alert %>
  <div class="alert alert-danger">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" id="errors">
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<div class="text-center">
  <div id="flash" style="display:none;">
    <% if notice %>
      <div class="bg-myrtle-dark">
        <%= notice %>
      </div>
    <% end %>
  </div>
</div>
<script>
  function sleep(msec) {
    return new Promise(function(resolve) {
      setTimeout(function() {resolve()}, msec);
    })
  };
  $(document).ready(function (){
    $('#flash').slideDown(1000,async function start(){
      await sleep(2000);
      $('#flash').slideUp(1000);
    });
  });
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container">
    <% if user_signed_in? %>
      <div class="navbar-brand">
        <%= link_to home_path do %>
          NELC
        <% end %>
      </div>
      <ul class="nav ml-auto">
        <li class="nav-link d-none d-sm-block">
          <%= link_to new_post_path do %>
            <i class="fas fa-edit"></i>
            <ruby>New Post<rt>とうこう</rt></ruby>
          <% end %>
        </li>
        <li class="nav-link">
          <%= link_to rooms_path do %>
            <i class="fas fa-comment-dots"></i>
            <ruby>Chat<rt>チャット</rt></ruby>
            <% if current_user.passive_notifications.chat.any? %>
              <span class="notification-badge"><%= current_user.passive_notifications.chat.size %></span>
            <% end %>
          <% end %>
        </li>
        <li class="nav-link d-none d-md-block">
          <%= link_to user_friends_path(current_user) do %>
            <i class="fas fa-user-friends"></i>
            <ruby>Friends<rt>ともだち</rt></ruby>
          <% end %>
        </li>
        <li class="nav-link d-lg-none">
          <%= link_to new_search_path do %>
            <i class="fas fa-search"></i>
          <% end %>
        </li>
        <li class="nav-link" id="notification_icon">
          <%= link_to notifications_path do %>
            <i class="fas fa-bell"></i>
            <% if current_user.passive_notifications.alerts.present? %>
              <span class="notification-badge"><%= current_user.passive_notifications.alerts.size %></span>
            <% end %>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" id="navbarDropdown" role="button" data-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
            <i class="fas fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <li class="dropdown-item">
              <%= link_to user_path(current_user) do %>
                Profile<small>　プロフィール</small>
              <% end %>
            </li>
            <li class="dropdown-item">
              <%= link_to new_post_path do %>
                New Post<small> とうこう</small>
              <% end %>
            </li>
            <li class="dropdown-item">
              <%= link_to bookmarks_path do %>
                Bookmarks<small>　ブックマーク</small>
              <% end %>
            </li>
            <li class="dropdown-item d-md-none">
              <%= link_to user_friends_path(current_user) do %>
                My Friends<small>　ともだち</small>
              <% end %>
            </li>
            <div class="dropdown-divider"></div>
            <li class="dropdown-item"><%= link_to "Log out", destroy_user_session_path, method: :delete %><small>　ログアウト</small></li>
          </ul>
        </li>
      </ul>
    <% else %>
      <div class="navbar-brand">
        <%= link_to root_path do %>
          NELC
        <% end %>
      </div>
      <ul class="nav">
        <li class="nav-link">
          <%= link_to new_user_registration_path do %>
            <i class="fas fa-user-plus"></i>
            <ruby>Join<rt>新規登録</rt></ruby>
          <% end %>
        </li>
        <li class="nav-link">
          <%= link_to new_user_session_path do %>
            <i class="fas fa-sign-in-alt"></i>
            <ruby>Log in<rt>ログイン</rt></ruby>
          <% end %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="d-none d-md-block col-md-3 col-lg-2 bg-light">
  <%= render "layouts/sidebar/user" %>
  <hr>
  <%= render "layouts/sidebar/menu" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NELC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="fixed-top">
      <% if admin_signed_in? %>
        <%= render "layouts/admin_header" %>
      <% else %>
        <%= render "layouts/header" %>
      <% end %>
      <%= render "layouts/flash" %>
    </header>
    <main>
      <div class="container-fluid">
        <%= yield %>
      </div>
    </main>
    <footer class="py-1">
      <div class="text-center">
        <p class="m-0">NELC</p> <div class="small text-right"><%= link_to "Community Guidelines | コミュニティ規約", policy_path %></div>
      </div>
    </footer>
  </body>
</html>